//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework_web_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cthd
    {
        public int macthd { get; set; }
        public Nullable<int> mahd { get; set; }
        public Nullable<int> masp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> thanhtien { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        public virtual sanpham sanpham { get; set; }
        public string tensp { get; internal set; }
    }
}
